# Generated by Django 4.2 on 2023-04-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Casts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("character", models.CharField(max_length=255)),
                ("actor", models.CharField(max_length=255)),
                (
                    "casts",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="movies.movie"
                    ),
                ),
            ],
        ),
    ]
