# Generated by Django 4.2 on 2023-04-14 02:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("casts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casts",
            old_name="casts",
            new_name="movie",
        ),
        migrations.RemoveField(
            model_name="casts",
            name="title",
        ),
    ]
