# Generated by Django 4.1.7 on 2023-04-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casts", "0003_casts_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="casts",
            name="age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="casts",
            name="deceased",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="casts",
            name="image",
            field=models.ImageField(upload_to="character/cast"),
        ),
    ]
