# Generated by Django 4.1.7 on 2023-04-14 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("casts", "0004_casts_age_casts_deceased_alter_casts_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casts",
            old_name="age",
            new_name="actor_age",
        ),
    ]
