# Generated by Django 4.1.7 on 2023-04-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casts", "0005_rename_age_casts_actor_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="casts",
            name="actor_image",
            field=models.ImageField(
                default="Mark_Hamill.jpg", upload_to="character/cast"
            ),
            preserve_default=False,
        ),
    ]
