# Generated by Django 4.2 on 2023-04-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.CharField(max_length=255)),
                ("genres", models.TextField()),
                ("number_Of_Films", models.IntegerField()),
                ("characters", models.CharField(max_length=255)),
                ("actor", models.CharField(max_length=255)),
                ("deceased", models.BooleanField(default=False)),
            ],
        ),
    ]
