# Generated by Django 4.2 on 2023-04-17 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.OneToOneField(
                default="unknown",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie",
                to="movies.director",
            ),
            preserve_default=False,
        ),
    ]
